

MAIN_WINDOW_MIN_HEIGHT = 200
MAIN_WINDOW_MIN_WIDTH = 700

GLOBAL_FONT = 'Tahoma'
SERVER_HEADER_COLUMN_FONT = 20
SERVER_INFO_FONT = 12

UP_COLOR = 'green'
DOWN_COLOR = 'red'

LABEL_DEFAULT_COLOR = 'green'