

MAIN_WINDOW_MIN_HEIGHT = 200
MAIN_WINDOW_MIN_WIDTH = 700

FRAME_MAIN_COLOR = 'SystemWindow'

GLOBAL_FONT = 'Tahoma'
SERVER_HEADER_COLUMN_FONT = 20
SERVER_INFO_FONT = 12

UP_COLOR = 'SystemButtonHighlight'
DOWN_COLOR = 'SystemActiveCaption'

LABEL_DEFAULT_COLOR = UP_COLOR